language: python
sudo: required
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.4"
 
services:
  - docker

env:
  matrix:
    - KV_DB=redis
    - KV_DB=zookeeper

# command to install dependencies
install: 
  - "pip install nstruct hiredis"
  - pip install coverage


# command to run tests
script: 
  - sudo -E bash -xe ci_test.sh


after_success:
  - bash <(curl -s https://codecov.io/bash)
